package br.com.pocketpos.server.orm;

/*
00 CLIENTE/FORNECEDOR
01 OPERADOR DE CAIXA
02 GERENTE
03 SUPERVISOR
04 EMPRESARIO/SOCIO PROPRIETARIO
05 ANALISTA DE SUPORTE
06 DESENVOLVEDOR
*/
public enum Level {

    CUSTOMER_SUPPLIER,
    CASHIER,
    MANAGER,
    SUPERVISOR,
    OWNER_PARTNER,
    SUPPORT_ANALYST,
    DEVELOPER

}