package br.com.developen.erp.orm;

/*
00 INDEFINIDO (BLOQUEADO)
01 CLIENTE/FORNECEDOR
02 OPERADOR DE CAIXA
03 GERENTE
04 SUPERVISOR
05 EMPRESARIO/SOCIO PROPRIETARIO
06 ANALISTA DE SUPORTE
07 DESENVOLVEDOR
*/
public enum Level {

	UNDEFINED,
    CUSTOMER_SUPPLIER,
    CASHIER,
    MANAGER,
    SUPERVISOR,
    OWNER_PARTNER,
    SUPPORT_ANALYST,
    DEVELOPER

}